# Generated by Django 5.2 on 2025-04-29 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beneficiario',
            name='nroCuenta',
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cuenta_beneficiaria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios_de', to='banco.cuenta'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='cuenta_propia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='banco.cuenta'),
        ),
    ]
