# Generated by Django 5.2 on 2025-05-01 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_remove_beneficiario_nrocuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_enviadas', to='banco.cuenta'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_recibidas', to='banco.cuenta'),
        ),
    ]
