# Generated by Django 5.2 on 2025-05-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_alter_transferencia_emisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
