# Generated by Django 5.2 on 2025-05-04 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_alter_transferencia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='cuenta_beneficiaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiarios_de', to='banco.cuenta'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='cuenta_propia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='banco.cuenta'),
        ),
    ]
